### PR TITLE
refactor: use new subdir /tmp for std-lib checkouts

### PR DESCRIPTION
**Pull request by bingcicle**
related: #230 #231 

starts a new Forc project within `.fuelup/tmp` sub directory instead of within `.fuelup`.

Reason:

there isn't a way to guarantee that the temporary directories created while fetching Forc dependencies (via init-ing and checking a Forc project) are cleaned up, especially if we kill the download before it finishes.

This is reproduced by installing forc (either by `fuelup toolchain install latest` or `fuelup component add forc`), getting to the part where we start fetching forc dependencies (terminal says `Fetching core forc dependencies`) and stopping/killing the process. We are left behind with a `temp-projectABCD` directory which is left uncleaned.
 
Solution can be to save all these temp projects within a sub directory `tmp`, and we try to clean up that directory instead, perhaps through another command.

### CODE REVIEW

**Review by Braqzen — COMMENTED** [review]
I'm unsure of the bigger picture but isn't there another PR which is supposed to remove touching the disk / create tmp files and instead do something in memory?

**Comment by bingcicle** [comment]
> I'm unsure of the bigger picture but isn't there another PR which is supposed to remove touching the disk / create tmp files and instead do something in memory?

Yup - though that was for the channel toml, and this will be to address fetching forc dependencies that we do in the background when installing the toolchain!

In #231 the entire toml file was previously being saved for 2 reasons: 

1) to use to compare versions - this was prior to having proper semver because of incorrect implementation on my part - see issue #190 and the accompanying PR #189, and 
2) it was convenient to use the same function `download_file` which we used to download the actual binaries anyway. 

The first has since been fixed by the PR linked above and 2) was just addressed in #231 where we use a different function where we do not persist the data as a file.

Now, for this PR, what installing `forc` does is that it checks out the std-lib to `~/.forc` by doing `forc init --path <path>` and `forc check --path <path>`, and this would've been done in a [tempdir](https://docs.rs/tempfile/latest/tempfile/fn.tempdir.html). However, there isn't a way to ensure that the destructors run (user could cancel/kill the process before completion, for example). This PR is supposed to use a subdir within `~/.fuelup` so that at least the base `.fuelup` directory isn't polluted, and that we have a dedicated `tmp` dir.

**Review by sdankel — APPROVED** [review]
> and we try to clean up that directory instead, perhaps through another command.

It makes sense that it'll be easier to clean if these files are in a separate subdirectory, but I'm curious what command will do the cleanup?

**Comment by bingcicle** [comment]
> It makes sense that it'll be easier to clean if these files are in a separate subdirectory, but I'm curious what command will do the cleanup?

For `rustup` there is an implicit cleanup done on every `rustup update`. I think going in line with what they're doing makes sense here, to do a cleanup on `fuelup update` (yet to be implemented, #208) or `fuelup self update`, and printing/logging a line to let the developer know that this is happening. I don't think it would be good for DevEx to have an explicit `fuelup clean` command to delete the contents of `/tmp` (though that may be an option as well) since it may not be immediately clear what the command would be for. Open to suggestions on this!

**Pull request merged**
