### PR TITLE
chore: bump indexer beta-4

### PR DESCRIPTION
**Pull request by ra0x3**
### Description

- PR simply bumps the indexer versions for the beta-4 toolchain

### CODE REVIEW

**Comment by JoshuaBatty** [comment]
Does it make sense to bump it for both release candidate versions?

**Comment by ra0x3** [comment]
@JoshuaBatty @kayagokalp Changes made (I think)

**Comment by kayagokalp** [comment]
Do you want to change beta-4 toolchain or beta-4-rc-2 toolchain? @ra0x3

**Comment by ra0x3** [comment]
@kayagokalp I changed the file prefixed with "-2" due to [this comment](https://github.com/FuelLabs/fuelup/pull/479#issuecomment-1699182137). Did I read it incorrectly (should I change the other one)?

**Comment by ra0x3** [comment]
One more attempt @kayagokalp  :)

**Comment by kayagokalp** [comment]
I think you wanted to change this one https://github.com/FuelLabs/fuelup/blob/gh-pages/channel-fuel-beta-4.toml instead of 
https://github.com/FuelLabs/fuelup/blob/gh-pages/channel-fuel-beta-4-rc.toml cc @ra0x3

**Pull request closed without merging**
